#!/bin/bash

backlight_path=/sys/class/backlight
device_name=${2:-$(ls $backlight_path | head -1)}
max_brightness=$(cat $backlight_path/$device_name/max_brightness 2>/dev/null)

# Check that a maximum brightness could be obtained
: ${max_brightness:?Could not get max brightness of device!}

current_brightness=$(cat $backlight_path/$device_name/brightness 2>/dev/null)

percentage_brightness=$( echo "$current_brightness / $max_brightness * 100" | bc -l) \

# Print the raw number if no arguments given
[[ -z $1 ]] && printf '{"text":"%s","tooltip":"%.0f%%","class":"","percentage":%.0f}\n' $current_brightness $percentage_brightness $percentage_brightness && exit 0

# Extract mods from string and apply them if applicable
setting=$1
[[ ${1: -1} == '%' ]] && setting=${1%\%} && setting=$( echo "${setting#+} / 100 * $max_brightness" | bc -l )
[[ ${1:0:1} == '+' || ${1:0:1} == '-' ]] && setting=$( echo "${setting#+} + $current_brightness" | bc -l )

[[ $(echo "$setting <= 1" | bc -l) == 1 ]] && setting=1
[[ $(echo "$setting > $max_brightness" | bc -l) == 1 ]] && setting=$max_brightness

# Set the brightness
brightness_file_path="/sys/class/backlight/$device_name/brightness"
value=$(printf '%.0f' $setting)
echo Setting brightness to: $value
echo Using backlight kernel display: $brightness_file_path
[[ -f $brightness_file_path ]] || echo Could not locate brightness file at: $brightness_file_path
echo $value > $brightness_file_path

exit $?
