#!/usr/bin/env sh

backlight_path=/sys/class/backlight
device_name=${2:-$(ls $backlight_path | head -1)}
max_brightness=$(cat $backlight_path/$device_name/max_brightness 2>/dev/null)

# Check that a maximum brightness could be obtained
: ${max_brightness:?Could not get max brightness of device!}

current_brightness=$(cat $backlight_path/$device_name/brightness 2>/dev/null)

percentage_brightness=$( echo "$current_brightness / $max_brightness * 100" | bc -l) \

# Print the raw number if no arguments given
if [ -z $1 ]; then
  printf '{"text":"%s","tooltip":"%.0f%%","class":"","percentage":%.0f}\n' $current_brightness $percentage_brightness $percentage_brightness
  exit 0
fi

# Extract mods from string and apply them if applicable
setting=$1
if [ ${1##${1%%?}} = '%' ]; then
  setting=${1%\%}
  setting=$( echo "${setting#+} / 100 * $max_brightness" | bc -l )
fi
first_character="${1%${1#?}}"
if [ ${first_character} = '+' -o ${first_character} = '-' ]; then
  setting=$( echo "${setting#+} + $current_brightness" | bc -l )
fi

if [ $(echo "$setting <= 1" | bc -l) = 1 ]; then
  setting=1
fi
if [ $(echo "$setting > $max_brightness" | bc -l) = 1 ]; then
  setting=$max_brightness
fi

# Set the brightness
brightness_file_path="/sys/class/backlight/$device_name/brightness"
value=$(printf '%.0f' $setting)
if [ ! -f $brightness_file_path ]; then
  echo Could not locate brightness file at: $brightness_file_path
fi
echo $value > $brightness_file_path

exit $?
