#!/bin/bash

state_path='/sys/power/state'
mem_sleep_path='/sys/power/mem_sleep'

suspend_to_mem() {
  echo 'Suspending to RAM...' >&2
  su -c "echo 'deep' > '$mem_sleep_path'"
  su -c "echo 'mem' > '$state_path'"
  echo 'Waking from RAM...' >&2
}

suspend_to_idle() {
  echo 'Suspending to Idle...' >&2

  state='freeze'

  echo Not Implemented! >&2
  return 1
}

poweron_standby() {
  echo 'Power-On Suspend...' >&2

  state='standby'

  echo Not Implemented! >&2
  return 1
}

suspend_to_disk() {
  echo 'Suspending to Disk (hibernating)...' >&2

  state='disk'

  echo Not Implemented! >&2
  return 1
}

showUsage() {
  echo Potential states: [$potential_states]
}

potential_states=$(cat /sys/power/state)
case $1 in
  '--help'|'-help'|'-h'|'help'|'h')
    showUsage
    exit 0
    ;;
esac

[[ ! -z $1 ]] && suspend_state=$1 || suspend_state='mem'

[[ ! -z "${potential_states##*$suspend_state*}" ]] && echo $suspend_state not in [$potential_states] && exit 1

case $suspend_state in
  'mem')
    suspend_to_mem
    ;;
  'freeze')
    suspend_to_idle
    ;;
  'disk')
    suspend_to_disk
    ;;
  'standby')
    poweron_standby
    ;;
esac
