#!/usr/bin/env sh

root_path="/sys/devices/platform/i8042"
path1="${root_path}/serio1"
path2="${root_path}/serio1/serio2"

trackpoint_path=$path1

if [ -e $path2 ]; then trackpoint_path=$path2; fi

if [ -z $1 ]; then
    echo Sensitivity: $(cat "${trackpoint_path}/sensitivity")
    speed_path="${trackpoint_path}/speed"
    if [ -e $speed_path ]; then echo Speed: $(cat "${speed_path}"); fi
    exit 0
fi

case $1 in
    "s")
        t="sensitivity"
        ;;
    "p")
        t="speed"
        ;;
    *)
        echo "Invalid argument!"
        exit -1
        ;;
esac

if [ -z $2 ]; then
    echo $(cat "${trackpoint_path}/${t}")
    exit 0
fi

setting=$2
echo -n $setting > "${trackpoint_path}/${t}"
exit $?

