#!/bin/bash

trackpoint_path=/sys/devices/platform/i8042/
device_name=${2:-$(ls $trackpoint_path/$serio1 | head -1)}

[[ -z $1 ]] && \
    echo Sensitivity: $(cat /sys/devices/platform/i8042/serio1/serio2/sensitivity) && \
    echo Speed: $(cat /sys/devices/platform/i8042/serio1/serio2/speed) && \
exit 0

case $1 in
    "s")
        t="sensitivity"
        ;;
    "p")
        t="speed"
        ;;
    *)
        echo "Invalid argument!" && exit -1
        ;;
esac

[[ -z $2 ]] && echo $(cat $trackpoint_path/serio1/serio2/$t) && exit 0

setting=$2
echo -n $setting > $trackpoint_path/serio1/serio2/$t
exit $?

