#!/usr/bin/env sh

state_path='/sys/power/state'
mem_sleep_path='/sys/power/mem_sleep'

potential_states=$(cat "${state_path}")
# It would be better to default this to valid value retrieved from $potential_states
suspend_state='mem'

suspend_to_mem() {
  echo "Suspending to RAM..." >&2
  echo "deep" > "${mem_sleep_path}" || return 2
}

suspend_to_idle() {
  echo "Suspending to Idle..." >&2

  echo "Not Implemented!" >&2
  return 1
}

poweron_standby() {
  echo "Power-On Suspend..." >&2

  echo "Not Implemented!" >&2
  return 1
}

suspend_to_disk() {
  echo "Suspending to Disk (hibernating)..." >&2
  echo "s2idle" > "${mem_sleep_path}" || return 2
}

showUsage() {
  echo "Potential states: [${potential_states}]"
  echo "Default is '${suspend_state}'"
}

case $1 in
  '--help'|'-help'|'-h'|'help'|'h')
    showUsage
    exit 0;;
esac

if [ ! -z $1 ]; then suspend_state=$1; fi

if [ ! -z "${potential_states##*$suspend_state*}" ]; then
  echo "${suspend_state} not in [${potential_states}]"
  exit 1
fi

case $suspend_state in
  'mem') suspend_to_mem;;
  'freeze') suspend_to_idle;;
  'disk') suspend_to_disk;;
  'standby') poweron_standby;;
esac

echo "${suspend_state}" > "${state_path}" || return 2
echo "Waking..." >&2

