#!/bin/bash

echo Starting backlight tests...
echo

tests_failed=0
sleep_time=5s

echo Running 'backlight' - should show current backlight value...
echo $(backlight)
[[ $? -ne 0 ]] && ((tests_failed++))
sleep $sleep_time

n=200
echo Running ''backlight $n'' - should set backlight to $n
echo $(backlight $n)
# Replace with an assert
[[ $? -ne 0 ]] && ((tests_failed++))
echo $(backlight)
sleep $sleep_time

n=+50
echo Running ''backlight $n'' - should increment backlight by $n
echo $(backlight $n)
# Replace with an assert
[[ $? -ne 0 ]] && ((tests_failed++))
echo $(backlight)
sleep $sleep_time

n=-50
echo Running ''backlight $n'' - should decrement backlight by $n
echo $(backlight $n)
# Replace with an assert
[[ $? -ne 0 ]] && ((tests_failed++))
echo $(backlight)
sleep $sleep_time

n=50%
echo Running ''backlight $n'' - should set backlight to $n
echo $(backlight $n)
# Replace with an assert
[[ $? -ne 0 ]] && ((tests_failed++))
echo $(backlight)
sleep $sleep_time

n=+50%
echo Running ''backlight $n'' - should increment backlight by $n
echo $(backlight $n)
# Replace with an assert
[[ $? -ne 0 ]] && ((tests_failed++))
echo $(backlight)
sleep $sleep_time

n=-50%
echo Running ''backlight $n'' - should decrement backlight by $n
echo $(backlight $n)
# Replace with an assert
[[ $? -ne 0 ]] && ((tests_failed++))
echo $(backlight)
sleep $sleep_time

echo
echo Tests failed: $tests_failed
exit $tests_failed

