#!/bin/bash

device=$(ls /sys/class/backlight)

n=200
echo Running ''backlight $n'' - should set backlight to $n
$(backlight $n)
backlight
brightness=$(cat /sys/class/backlight/$device/brightness)
[[ $brightness -ne $n ]] && exit 1 || exit 0

