#!/bin/bash

device=$(ls /sys/class/backlight)

n=-50
echo Running ''backlight $n'' - should decrement backlight by $n
before_brightness=$(cat /sys/class/backlight/$device/brightness)
$(backlight $n)
after_brightness=$(cat /sys/class/backlight/$device/brightness)
check_brightness=$(( before_brightness $n ))
echo $after_brightness $check_brightness
[[ $after_brightness -ne $check_brightness ]] && exit 1 || exit 0

