#!/bin/bash

device=$(ls /sys/class/backlight)
backlight_path=/sys/class/backlight

function GetCurrentBrightness {
    echo $(cat $backlight_path/$device/brightness 2>/dev/null)
}

function GetAbsoluteFromPercent {
    max=$(cat $backlight_path/$device/max_brightness 2>/dev/null)
    relative=$(printf "%.0f" $( echo "$max * $1 / 100" | bc -l ))
    echo $relative
}

tests_failed=0
sleep_time=5s

echo Running \"backlight\"
backlight > /dev/null
ex=$?
(( ex == 0 )) || ((tests_failed++))

echo Running \"backlight %\"
backlight % > /dev/null
ex=$?
(( ex == 0 )) || ((tests_failed++))

echo Running \"backlight 200\"
backlight 200 > /dev/null
ex=$?
(( $(GetCurrentBrightness) == 200 && ex == 0 )) || ((tests_failed++))

echo Running \"backlight +2\"
current=$(GetCurrentBrightness)
backlight +2 > /dev/null
ex=$?
(( $(GetCurrentBrightness) == current + 2 && ex == 0 )) || ((tests_failed++))

echo Running \"backlight -2\"
current=$(GetCurrentBrightness)
backlight -2 > /dev/null
ex=$?
(( $(GetCurrentBrightness) == current - 2 && ex == 0 )) || ((tests_failed++))

echo Running \"backlight 50%\"
current=$(GetCurrentBrightness)
backlight 50% > /dev/null
ex=$?
check=$(printf "%.0f" $(GetAbsoluteFromPercent 50))
(( $(GetCurrentBrightness) == check && ex == 0 )) || ((tests_failed++))

echo Running \"backlight +5%\"
current=$(GetCurrentBrightness)
backlight +5% > /dev/null
ex=$?
check=$(( $(GetAbsoluteFromPercent 50) + $(GetAbsoluteFromPercent 5) ))
(( $(GetCurrentBrightness) == check && ex == 0 )) || ((tests_failed++))

echo Running \"backlight -5%\"
current=$(GetCurrentBrightness)
backlight -5% > /dev/null
ex=$?
check=$(GetAbsoluteFromPercent 50)
(( $(GetCurrentBrightness) == check && ex == 0 )) || ((tests_failed++))

echo
echo Tests failed: $tests_failed
exit $tests_failed

